# -*- coding: utf-8 -*-
"""Lab 4 Data Science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HKxI19y4tK-X572MdLmzfIlGHYCv4JXy

Question 1
"""

import math
import matplotlib.pyplot as plt
import numpy as np

t = np.linspace(3*-np.pi,3*np.pi)
plt.ylim(-4, 4)
plt.xlim(-10, 10)
x = [i*(np.pi/180) for i in t]
plt.plot(t,np.sin(t)*2,"-b", label='2sin')
plt.plot(t,np.cos(t)*2,"--r", label='2cos')
plt.grid(color="green", alpha = 0.2)
plt.title("Sin and Cos graph")
plt.xlabel('X', fontsize = 15) 
plt.ylabel('Y', fontsize = 15) 
plt.legend()

"""Question 2"""

X = np.random.rand(1000) * 100
Y = np.random.normal(50, 10, 1000)

meanx = X.mean() #mean of x
stdx = X.std() #standard deviation of x
meany = Y.mean() #Mean of y
stdy = Y.std() #standard deviation of y

plt.hist(X, bins=20, alpha= 0.5, label='X', edgecolor='black')
plt.hist(Y, bins=20, alpha= 0.5, label='Y', edgecolor='black')
plt.legend() #legend
plt.show()  #show the histograph